# Generated by Django 6.0.3 on 2026-04-03 04:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nome exibido para a forma de pagamento.', max_length=50, unique=True, verbose_name='nome')),
                ('code', models.SlugField(blank=True, help_text='Identificador interno estável da forma de pagamento.', max_length=100, unique=True, verbose_name='código')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se a forma de pagamento pode ser usada em novos lançamentos.', verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Forma de pagamento',
                'verbose_name_plural': 'Formas de pagamento',
                'db_table': 'clinic_paymentmethod',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AppointmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method_name_snapshot', models.CharField(blank=True, help_text='Nome da forma de pagamento congelado no momento do lançamento.', max_length=100, verbose_name='nome da forma de pagamento')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor pago neste item de pagamento.', max_digits=10, verbose_name='valor pago')),
                ('doctor_percentage', models.DecimalField(decimal_places=2, help_text='Percentual do item destinado ao médico no momento do lançamento.', max_digits=5, verbose_name='percentual do médico')),
                ('clinic_percentage', models.DecimalField(decimal_places=2, help_text='Percentual do item destinado à clínica no momento do lançamento.', max_digits=5, verbose_name='percentual da clínica')),
                ('doctor_amount', models.DecimalField(decimal_places=2, help_text='Valor do item destinado ao médico.', max_digits=10, verbose_name='valor do médico')),
                ('clinic_amount', models.DecimalField(decimal_places=2, help_text='Valor do item destinado à clínica.', max_digits=10, verbose_name='valor da clínica')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora em que o pagamento foi registrado.', verbose_name='recebido em')),
                ('appointment', models.ForeignKey(help_text='Consulta à qual este pagamento pertence.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clinic.appointment', verbose_name='consulta')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que registrou este pagamento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointment_payments', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('payment_method', models.ForeignKey(help_text='Forma de pagamento utilizada neste item.', on_delete=django.db.models.deletion.PROTECT, related_name='appointment_payments', to='payments.paymentmethod', verbose_name='forma de pagamento')),
            ],
            options={
                'verbose_name': 'Pagamento da consulta',
                'verbose_name_plural': 'Pagamentos das consultas',
                'db_table': 'clinic_appointmentpayment',
            },
        ),
        migrations.CreateModel(
            name='DoctorPaymentSplitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_percentage', models.DecimalField(decimal_places=2, help_text='Percentual do valor pago que pertence ao médico.', max_digits=5, verbose_name='percentual do médico')),
                ('clinic_percentage', models.DecimalField(decimal_places=2, help_text='Percentual do valor pago que pertence à clínica.', max_digits=5, verbose_name='percentual da clínica')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se esta regra pode ser usada nas novas consultas.', verbose_name='ativo')),
                ('doctor', models.ForeignKey(help_text='Médico ao qual a regra de repasse pertence.', on_delete=django.db.models.deletion.PROTECT, related_name='payment_split_rules', to='clinic.doctor', verbose_name='médico')),
                ('payment_method', models.ForeignKey(help_text='Forma de pagamento coberta por esta regra.', on_delete=django.db.models.deletion.PROTECT, related_name='doctor_payment_split_rules', to='payments.paymentmethod', verbose_name='forma de pagamento')),
            ],
            options={
                'verbose_name': 'Regra de repasse',
                'verbose_name_plural': 'Regras de repasse',
                'db_table': 'clinic_doctorpaymentsplitrule',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('doctor', 'payment_method'), name='unique_active_split_rule_per_doctor_payment_method')],
            },
        ),
    ]
