# Generated by Django 6.0.3 on 2026-03-28 04:07

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluído em')),
                ('full_name', models.CharField(help_text='Nome completo do paciente.', max_length=255, verbose_name='nome completo')),
                ('birth_date', models.DateField(blank=True, help_text='Data de nascimento do paciente.', null=True, verbose_name='data de nascimento')),
                ('sex', models.CharField(blank=True, help_text='Sexo do paciente.', max_length=20, null=True, verbose_name='sexo')),
                ('cpf', models.CharField(blank=True, help_text='CPF do paciente.', max_length=14, null=True, verbose_name='cpf')),
                ('notes', models.TextField(blank=True, help_text='Observacoes gerais sobre o paciente.', null=True, verbose_name='observacao')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluído em')),
                ('full_name', models.CharField(help_text='Nome completo do medico.', max_length=255, verbose_name='nome completo')),
                ('specialty', models.CharField(help_text='Especialidade principal do medico.', max_length=255, verbose_name='especialidade')),
                ('crm', models.CharField(help_text='Numero de registro CRM do medico.', max_length=50, verbose_name='crm')),
                ('notes', models.TextField(blank=True, help_text='Observacoes gerais sobre o medico.', null=True, verbose_name='observacao')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o medico esta ativo para atendimento.', verbose_name='ativo')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluído em')),
                ('email', models.EmailField(help_text='Endereco de email cadastrado.', max_length=254, verbose_name='email')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluído em')),
                ('number', models.CharField(help_text='Numero de telefone cadastrado.', max_length=20, verbose_name='numero')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluído em')),
                ('consultation_type', models.CharField(choices=[('first_consultation', 'Primeira consulta'), ('return', 'Retorno')], help_text='Tipo da consulta realizada.', max_length=30, verbose_name='tipo de consulta')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Valor pago pelo paciente na consulta.', max_digits=10, verbose_name='valor pago')),
                ('payment_method', models.CharField(choices=[('money', 'Dinheiro'), ('pix', 'Pix'), ('credit_card', 'Cartao de Credito'), ('debit_card', 'Cartao de Debito')], help_text='Forma de pagamento utilizada na consulta.', max_length=20, verbose_name='forma de pagamento')),
                ('notes', models.TextField(blank=True, help_text='Observacoes gerais sobre a consulta.', null=True, verbose_name='observacao')),
                ('client', models.ForeignKey(help_text='Paciente vinculado a consulta.', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.client', verbose_name='paciente')),
                ('doctor', models.ForeignKey(help_text='Medico responsavel pela consulta.', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.doctor', verbose_name='medico')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='emails',
            field=models.ManyToManyField(blank=True, help_text='Emails vinculados ao medico.', related_name='doctors', to='clinic.email', verbose_name='emails'),
        ),
        migrations.AddField(
            model_name='client',
            name='emails',
            field=models.ManyToManyField(blank=True, help_text='Emails vinculados ao paciente.', related_name='clients', to='clinic.email', verbose_name='emails'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phones',
            field=models.ManyToManyField(blank=True, help_text='Telefones vinculados ao medico.', related_name='doctors', to='clinic.phone', verbose_name='telefones'),
        ),
        migrations.AddField(
            model_name='client',
            name='phones',
            field=models.ManyToManyField(blank=True, help_text='Telefones vinculados ao paciente.', related_name='clients', to='clinic.phone', verbose_name='telefones'),
        ),
    ]
