# Generated by Django 6.0.3 on 2026-04-03 04:20

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDailySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_date', models.DateField(unique=True, verbose_name='data da sequência')),
                ('last_value', models.PositiveIntegerField(default=0, verbose_name='último valor')),
            ],
            options={
                'verbose_name': 'Sequência diária de consulta',
                'verbose_name_plural': 'Sequências diárias de consulta',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluído em')),
                ('full_name', models.CharField(help_text='Nome completo do paciente.', max_length=255, verbose_name='nome completo')),
                ('birth_date', models.DateField(help_text='Data de nascimento do paciente.', verbose_name='data de nascimento')),
                ('sex', models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino')], help_text='Sexo do paciente.', max_length=20, verbose_name='sexo')),
                ('cpf', models.CharField(blank=True, help_text='CPF do paciente.', max_length=14, null=True, verbose_name='cpf')),
                ('phone_primary', models.CharField(blank=True, help_text='Telefone principal do paciente.', max_length=20, verbose_name='telefone principal')),
                ('phone_secondary', models.CharField(blank=True, help_text='Telefone secundario do paciente.', max_length=20, verbose_name='telefone secundario')),
                ('email', models.EmailField(blank=True, help_text='Email do paciente.', max_length=254, verbose_name='email')),
                ('notes', models.TextField(blank=True, help_text='Observacoes gerais sobre o paciente.', null=True, verbose_name='observacao')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluído em')),
                ('full_name', models.CharField(help_text='Nome completo do medico.', max_length=255, verbose_name='nome completo')),
                ('crm', models.CharField(help_text='Numero de registro CRM do medico.', max_length=50, verbose_name='crm')),
                ('phone_primary', models.CharField(blank=True, help_text='Telefone principal do medico.', max_length=20, verbose_name='telefone principal')),
                ('phone_secondary', models.CharField(blank=True, help_text='Telefone secundario do medico.', max_length=20, verbose_name='telefone secundario')),
                ('email', models.EmailField(blank=True, help_text='Email do medico.', max_length=254, verbose_name='email')),
                ('notes', models.TextField(blank=True, help_text='Observacoes gerais sobre o medico.', null=True, verbose_name='observacao')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o medico esta ativo para atendimento.', verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluído em')),
                ('name', models.CharField(help_text='Nome da especialidade medica.', max_length=255, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluído em')),
                ('code', models.CharField(blank=True, editable=False, help_text='Código único para localização operacional da consulta.', max_length=20, unique=True, verbose_name='código da consulta')),
                ('consultation_type', models.CharField(choices=[('first_consultation', 'Primeira consulta'), ('return', 'Retorno'), ('aso', 'ASO'), ('procedure', 'Procedimento')], help_text='Tipo da consulta realizada.', max_length=30, verbose_name='tipo de consulta')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Valor total da consulta, que deve bater com a soma dos pagamentos.', max_digits=10, verbose_name='valor total')),
                ('notes', models.TextField(blank=True, help_text='Observacoes gerais sobre a consulta.', null=True, verbose_name='observacao')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que criou a consulta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('client', models.ForeignKey(help_text='Paciente vinculado a consulta.', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.client', verbose_name='paciente')),
                ('doctor', models.ForeignKey(help_text='Medico responsavel pela consulta.', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.doctor', verbose_name='medico')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(blank=True, help_text='Especialidades vinculadas ao medico.', related_name='doctors', to='clinic.specialty', verbose_name='especialidades'),
        ),
    ]
