# Generated by Django 6.0.3 on 2026-03-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('money', 'Dinheiro'), ('pix', 'Pix'), ('credit_card', 'Cartao de Credito'), ('debit_card', 'Cartao de Debito'), ('health_insurance', 'Plano de Saude')], help_text='Forma de pagamento utilizada na consulta.', max_length=20, verbose_name='forma de pagamento'),
        ),
    ]
